# Generated by Django 5.0.3 on 2024-05-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDSapp', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('companyPos', models.CharField(max_length=50)),
                ('passportNo', models.CharField(max_length=15)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Lodged', 'Lodged'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Archived', 'Archived')], max_length=20)),
                ('applicationType', models.CharField(choices=[('Renewal', 'Renewal'), ('Application', 'Application')], max_length=20)),
                ('documentType', models.CharField(choices=[('Visa', 'Visa'), ('Passport', 'Passport'), ('Work Permit', 'Work Permit')], max_length=20)),
                ('businessUnit', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeletedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('companyPos', models.CharField(max_length=50)),
                ('passportNo', models.CharField(max_length=15)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Lodged', 'Lodged'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Archived', 'Archived')], max_length=20)),
                ('applicationType', models.CharField(choices=[('Renewal', 'Renewal'), ('Application', 'Application')], max_length=20)),
                ('documentType', models.CharField(choices=[('Visa', 'Visa'), ('Passport', 'Passport'), ('Work Permit', 'Work Permit')], max_length=20)),
                ('businessUnit', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
