# Generated by Django 5.0.1 on 2024-05-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDSapp', '0004_applicationarchive_deletedapplication'),
        ('IDSapp', '0005_checklist_country_checklist_documenttype'),
    ]

    operations = [
    ]
