# Generated by Django 5.0.1 on 2024-05-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDSapp', '0006_merge_20240503_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.RemoveField(
            model_name='application',
            name='middleName',
        ),
    ]
