# Generated by Django 5.0.1 on 2024-05-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDSapp', '0007_remove_account_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
