# Generated by Django 5.0.1 on 2024-05-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDSapp', '0008_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IDSapp.checklist'),
        ),
        migrations.AddField(
            model_name='applicationarchive',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IDSapp.checklist'),
        ),
        migrations.AddField(
            model_name='deletedapplication',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IDSapp.checklist'),
        ),
    ]
