# Generated by Django 5.0.1 on 2024-05-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDSapp', '0009_application_checklist_applicationarchive_checklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='passportNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applicationarchive',
            name='passportNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='deletedapplication',
            name='passportNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
